on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    branches:
      - main
      - master

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
